# Generated by Django 4.0.5 on 2022-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_item_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='videotitle',
            field=models.CharField(default=0, max_length=800),
        ),
    ]
